# Generated by Django 2.1.7 on 2019-05-01 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reg_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Structure.Person')),
                ('conviction', models.BooleanField()),
                ('work', models.BooleanField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('Structure.person',),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('moneyoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Structure.MoneyOperation')),
                ('end_date', models.DateField()),
            ],
            bases=('Structure.moneyoperation',),
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('operationtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Structure.OperationType')),
            ],
            bases=('Structure.operationtype',),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('moneyoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Structure.MoneyOperation')),
                ('end_date', models.DateField()),
            ],
            bases=('Structure.moneyoperation',),
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('operationtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Structure.OperationType')),
            ],
            bases=('Structure.operationtype',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Structure.Person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Structure.person',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('moneyoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Structure.MoneyOperation')),
            ],
            bases=('Structure.moneyoperation',),
        ),
        migrations.AddField(
            model_name='moneyoperation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structure.Department'),
        ),
        migrations.AddField(
            model_name='moneyoperation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structure.Status'),
        ),
        migrations.AddField(
            model_name='moneyoperation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structure.Client'),
        ),
        migrations.AddField(
            model_name='moneyoperation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structure.Employee'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structure.DepositType'),
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structure.CreditType'),
        ),
    ]
